"""added user admin

Revision ID: 181347289903
Revises: 06df1ecd41fd
Create Date: 2021-11-19 12:45:36.551243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181347289903'
down_revision = '06df1ecd41fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasklogin-users', sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasklogin-users', 'is_admin')
    # ### end Alembic commands ###
